# Build Gstle in a stock Go builder container
FROM golang:1.12-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

ADD . /go-saintlignediuma
RUN cd /go-saintlignediuma && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /go-saintlignediuma/build/bin/* /usr/local/bin/

EXPOSE 6134 6135 30410 30410/udp
